### ISSUE TITLE
cgroups v2 on wsl2?

### ISSUE THREAD

**Issue by NickWoodward** [btholt/project-files-for-complete-intro-to-containers-v2#1]
So the docs for the course say that cgroups v2 is now the standard and that rather than upgrade v1 we should upgrade linux - But I don't think that's true on WSL2? I seems to be running a hybrid of v1 and v2.

There seems to be a solution of sorts here: https://stackoverflow.com/questions/73021599/how-to-enable-cgroup-v2-in-wsl2

but in all honesty this seems a little involved if I've no practical need to do this for the rest of the course? (I'm assuming in the next lesson that docker takes care of all of this?)

Thanks!

Loving the course btw :)

*edit: thinking about it maybe the hybrid version allows me to follow along regardless?
**edit2: at least some of the options aren't available `cpu.max` for example

**Comment by dtauer** [comment]
Yes, definitely not something you need to do for the purpose of this course. Docker handles all that for you. You can read more about [cgroups v1 moving to maintenance mode](https://kubernetes.io/blog/2024/08/14/kubernetes-1-31-moving-cgroup-v1-support-maintenance-mode/) if you are interested.
